---
- name: Download Papertrail PEM
  get_url:
    url: https://papertrailapp.com/tools/papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
    mode: 0644

- name: Download remote_syslog
  get_url:
    url: "https://github.com/papertrail/remote_syslog2/releases/download/v{{ papertrail.version }}/remote_syslog_linux_amd64.tar.gz"
    dest: "/usr/local/src/remote_syslog_{{ papertrail.version }}_linux_amd64.tar.gz"

- name: Unarchive remote_syslog
  unarchive:
    src: "/usr/local/src/remote_syslog_{{ papertrail.version }}_linux_amd64.tar.gz"
    dest: "{{ remote_syslog.dir }}"
    copy: no
    creates: "{{ remote_syslog.dir }}/remote_syslog"

- name: Configure Papertrail
  template:
    src: log_files.yml.j2
    dest: /etc/log_files.yml

- name: Configure Rsyslog to use Papertrail
  template:
    src: 90-papertrail.conf.j2
    dest: /etc/rsyslog.d/90-papertrail.conf
  notify:
    - Restart Rsyslog

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
