---
- name: Install rsyslog-gnutls for TLS supporting
  apt:
    name: rsyslog-gnutls
    state: present

- name: Configure Papertrail service definition
  template:
    src: remote_syslog.upstart.conf.j2
    dest: /etc/init/remote_syslog.conf
  notify:
    - Restart remote_syslog
