---
- name: Playbook - Papertrail installation
  hosts: "papertrail"
  sudo: true

  roles:
    - role: ansible-papertrail
      papertrail:
        logs:
          - { path: /var/log/auth.log, comment: 'Auth logs'  }
          - { path: /var/log/nginx/*.log, comment: 'All nginx logs'  }
