Vagrant.configure("2") do |config|
  config.vm.box = "parallels/ubuntu-14.04"
  config.vm.provider "parallels" do |config|
    config.memory = 2048
    config.cpus = 2
  end

  config.vm.define "papertrail" do |papertrail|
    papertrail.vm.host_name = 'papertrail'
    papertrail.vm.network "private_network", ip: "192.168.10.10"
    papertrail.vm.provision "ansible" do |ansible|
      ansible.playbook = "papertrail.yml"
      ansible.inventory_path = "inventory"
      ansible.limit = 'all'
      #ansible.ask_vault_pass = true
    end
  end

end
